server:
    port: 8888
    content-path: /

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/soa,classpath:/config/op
          add-label-locations:
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: false