server:
  port: 8082
spring:
  application:
    name: soa
  cloud:
    config:
      name: soa
      profile: dev


eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳间隔，5秒
    lease-expiration-duration-in-seconds: 10 #没有心跳的淘汰时间
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    register-with-eureka: true
    fetch-registry: false
