server:
  port: 8761
  content-path: /

spring:
  application:
    name: eureka-server

eureka:
  server:
    enable-self-preservation: false  #自我保护模式
    eviction-interval-timer-in-ms: 5000 #主动失效检测间隔
    use-read-only-response-cache: false
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost