/* https://github.com/orange1438 */
package com.blackie.soa.client.model.po.test.mbg;

public class UserTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.id
     * 主键
     * @author orange1438 code generator
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.mobile
     * 手机号码
     * @author orange1438 code generator
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.name
     * 姓名
     * @author orange1438 code generator
     */
    private String name;

    /** 
     * 获取 主键 user_test.id
     * @return 主键
     */
    public Integer getId() {
        return id;
    }

    /** 
     * 设置 主键 user_test.id
     * @param id 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /** 
     * 获取 手机号码 user_test.mobile
     * @return 手机号码
     */
    public String getMobile() {
        return mobile;
    }

    /** 
     * 设置 手机号码 user_test.mobile
     * @param mobile 手机号码
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /** 
     * 获取 姓名 user_test.name
     * @return 姓名
     */
    public String getName() {
        return name;
    }

    /** 
     * 设置 姓名 user_test.name
     * @param name 姓名
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", mobile=").append(mobile);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}